# Generated by Django 5.2.1 on 2025-06-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.CharField(default='avatar1.png', max_length=100),
        ),
    ]
